### ISSUE TITLE
Can't reopen SimpleChildWindow

### ISSUE THREAD

**Issue by riegaz** [punker76/MahApps.Metro.SimpleChildWindow#10]
Could you please help me? Once closed the window it does not reopen. With the code below you should be able to verify this behaviour.

It should open and close every 3 seconds but it never reopens.

Thanks for help!

In XAML:
```xaml
simpleChildWindow:ChildWindow IsOpen="{Binding showwarning}"
```

In a task I run:
```csharp
 while (true)
            {
                Thread.Sleep(3000);
                if (showwarning)
                { showwarning = false; Console.WriteLine("OFF"); }
                else
                { showwarning = true; Console.WriteLine("ON"); }
            }
```
showwarning is of type (typical wpf structure):
```csharp
private bool _showwarning = false;
        public bool showwarning
        {
            get
            { return _showwarning; }
            set
            {
                //Console.WriteLine("change");
               // if (_showwarning == value) { return; }
                _showwarning = value;
                RaisePropertyChanged("showwarning");
            }
        }
```

**Comment by punker76** [comment]
@riegaz i've implemented this short example in the demo and it works on my machine™

![test](https://cloud.githubusercontent.com/assets/658431/6543112/2f85180a-c50f-11e4-890e-d4a8c4446afc.gif)

**Comment by riegaz** [comment]
I checked your examples. You set the "IsOpen" in the code behind but not via a Binding. For me like this it is also working but once I bind it, it does only work once.

Here is a basic example.

https://mega.co.nz/#!vwoBCSbR!BdwRvnu2rjgzfxQu0KXgfj32PgOyEw3Uc4wc8UEpzvQ

**Comment by riegaz** [comment]
Can you reproduce the behaviour?

**Comment by riegaz** [comment]
Please let me know if you plan to fix this problem, because I'm waiting right now for your response. Any response is welcome, I just need to know if I have to implement something on my own.

**Comment by punker76** [comment]
@riegaz i really don't know what's going wrong here, but i'll look into

**Comment by riegaz** [comment]
Thank you. I used a converter to convert the bound variable from number to boolean. Once the subwindow does not respond anymore, also the converter does not get notified anymore. It looks like the dependencyobject is somehow unregistered or overwritten vor lost? Maybe it would be interesting to see if it happens from on to offand also from off to on.

**Comment by merso0027** [comment]
I have same issue.
Do you have any solution for this?

**Comment by punker76** [comment]
@merso0027 do you also use MVVMLight?

**Comment by agc93** [comment]
I see you've removed it from 1.2.0. Has there been any progress on this? Or do we need to roll our own replacement just to get MVVM Binding working?

I have the same issue using only the built-in WPF Bindings and properties, no MVVMLight or other frameworks. Same issue: can be toggled on, then off, and then no longer responds.

**Comment by punker76** [comment]
@riegaz @merso0027 @agc93 you can test the 1.3.0-ALPHA001 which should fix this nasty bug...

**Comment by agc93** [comment]
Just wanted to confirm and say that the new version works like a dream for me. Installed from the prerelease Nuget package, worked first time. Thanks heaps!!
