### ISSUE TITLE
ChildWindow position when it appears.

### ISSUE THREAD

**Issue by DeputyOfCopyPaster** [punker76/MahApps.Metro.SimpleChildWindow#103]
hello everyone!
Is there a way to set a certain ChildWindow position when it appears? At the moment it appears exact in the middle of the screen and even I move it to a certain place, next time (after App restart), it appears in the middle of the screen as it was before.
Is there a way to save this position?

thanks in advance!

**Comment by timunie** [comment]
Hi @DeputyOfCopyPaster If I remember correctly you can use the Margin property to define the position of a child window.  I don't have a PC at the moment so i could not check it right now. 

Happy coding Tim

**Comment by DeputyOfCopyPaster** [comment]
> 
> 
> Hi @DeputyOfCopyPaster If I remember correctly you can use the Margin property to define the position of a child window. I don't have a PC at the moment so i could not check it right now.
> 
> Happy coding Tim

I don't think so, the Margin isn't a proper way to do that. 
There should be a cleverer way, definetely.
So. please check it and tell me how to do that by a proper way.

thanks in advance!

**Comment by timunie** [comment]
Hi @DeputyOfCopyPaster ,
I had a look in the source code and as far as I can see (I'm not a programmer ;-) ) there is currently no buit in way to save the window position...

**Workaround**
You are correct, it wasn't `Margin` that I was looking for, it was `Padding`. You can take this property as a work around:
Let`s assume you have the following parameters set:
```
 VerticalContentAlignment = VerticalAlignment.Top;
 HorizontalContentAlignment = HorzontalAlignment.Left;
```
When you close the `ChildWindow` you have to calculate the offset from left and top and save these value somewhere, e.g. in the `Properties`. When you call the `ChildWindow` again, you can then initilize it with these values: 
```
Padding = new Thickness(SavedLeftPosition, SavedTopPosition, 0, 0);
```
But please keep in mind, the `MainWindow` may have changed it's size and the `ChildWindow` might be outside of the `MainWindow`. This has to be cached I think. 

**Built in soultion**
As far as I can see there has to be two new `Properties` `OffsetX` and `OffsetY` to enable what you are looking for. I don't know if @punker76 wants this feature or not. If he gives me the go, I will *try* to implement these `Properties`. 

Happy coding 
Tim

**Comment by DeputyOfCopyPaster** [comment]
@timunie, hello
I went to #104 and had taken a look at animated GIF.  
I'm afraid you missed the point of my issue.  The ChWindow behaviour  you had shown in #104 was available as long as 2018. Please see my animation. It's ChWindow test I performed in 2018 for myself.
It remembers its position easily within App session. 
So, what is going to happen in case when you close App and reopen. Does ChWindow remembers its latter position?

thanks in advance!
![ChWindow2018](https://user-images.githubusercontent.com/43616343/66721846-9b5d1680-ee0f-11e9-93e5-c45534796cb6.gif)

**Comment by timunie** [comment]
Hi @DeputyOfCopyPaster ,

I took another gif to show you that it is possible to remember the position (I see you got it and changed your question, but I am already done with the new gif :-) ).

![ChildWindow_RememberPosition](https://user-images.githubusercontent.com/47110241/66731578-5ad5bb00-ee58-11e9-9b46-03e035ff86b3.gif)

Happy coding
Tim

**Comment by DeputyOfCopyPaster** [comment]
@timunie, hi there
Coulld yuo tell me where have done changes? ChWindow version?
![release](https://user-images.githubusercontent.com/43616343/66736251-5ff33400-ee71-11e9-8b89-b060e745a872.png)

**Comment by timunie** [comment]
@DeputyOfCopyPaster, at the moment it is just a PR. I don't know if it will be ever available, @punker76 has to decide :+1: or :-1:

**Comment by DeputyOfCopyPaster** [comment]
Why not? Missing of that just deprives ChWindow of some usability, I believe.
the ChWindows must pop up at place where it was planned by end user. :+1:

**Comment by timunie** [comment]
I am not the owner of this repro and don't have write permissions, so I am unable to do.

**Comment by DeputyOfCopyPaster** [comment]
never mind, hope owners follow our chat...

**Comment by DeputyOfCopyPaster** [comment]
@timunie, @punker76,
Guys, I am not familiar with Github system at all, so please enlighten me what is the status of this ChWindow feature. May I use it?

thank you!

**Comment by timunie** [comment]
@DeputyOfCopyPaster yes if you uae the latest prerelease

**Comment by DeputyOfCopyPaster** [comment]
> 
> 
> @DeputyOfCopyPaster yes if you uae the latest prerelease

How do I find the latest prerelease?

**Comment by timunie** [comment]
Hi @DeputyOfCopyPaster ,

sorry for the late replay. Set this checkmark in your Nuget-Manager: 
![image](https://user-images.githubusercontent.com/47110241/67554623-0cee6c00-f710-11e9-92e2-8f09fbf5ff03.png)

Happy testing
Tim

**Comment by DeputyOfCopyPaster** [comment]
@timunie, 
hi there,
just assembled a test project based on yours **_all latest prereleases_**, as you shaowed me above.
Perhaps I missed something. The ChildWindow still doesn't remember its position.
Today is Monday, though... :)
![ChWindow_01](https://user-images.githubusercontent.com/43616343/67661109-6b665500-f971-11e9-86fb-774d6ae7e0f5.gif)

**Comment by timunie** [comment]
Hi @DeputyOfCopyPaster ,
As you can have more than one CW that you might want to rember, there is no build in way to save the position. You will need to save `OffsetX` and `OffsetY` on your own. see: https://docs.microsoft.com/de-de/visualstudio/ide/managing-application-settings-dotnet?view=vs-2015&redirectedfrom=MSDN

Happy coding 
Tim

**Comment by DeputyOfCopyPaster** [comment]
@timunie, it seems I've gotten a remembering of ChWindow previous position.
However, why  I'm getting at left upper corner -negative values and at right lower corner -positive values? As per GIF attached. Please give me an idea.


![neg_values](https://user-images.githubusercontent.com/43616343/67675132-7334f200-f98f-11e9-875d-ce8ed937ca20.gif)

**Comment by timunie** [comment]
@DeputyOfCopyPaster it depends on the HorizontalAlignment and VerticalAlignment

**Comment by DeputyOfCopyPaster** [comment]
@timunie. I don't see any alignment properties used in your latter demo release.

**Comment by timunie** [comment]
the default is center, so the Point (0,0) is in the middle ...

**Comment by DeputyOfCopyPaster** [comment]
@timunie, while playing around I've noticed one more thing which brings some discomfort in ChildWindow usage. As practice shows, the left upper ChildWindow's corner (mostly it's icons area) is not sensetive for dragging. In other words it doesn't allow to hide ChildWindow more deeper. 
It's possible to hide a bit more, though.
@timunie, look, I'm not speaking about hiding **_entirely_**, I'm speaking about hiding a bit more than we have at the moment.

So, what do you think about?

![ChWindow_icon](https://user-images.githubusercontent.com/43616343/67678811-944e1080-f998-11e9-9e51-450bd3b108d5.gif)

**Comment by timunie** [comment]
to be honest I don't see a reason why one should move the childwindow out of the parent window. Maybe you should consider to open a new `MetroWindow`.

Happy dragging
Tim

**Comment by DeputyOfCopyPaster** [comment]
> 
> 
> to be honest I don't see a reason why one should move the childwindow out of the parent window. Maybe you should consider to open a new `MetroWindow`.
> 
> Happy dragging
> Tim

@timunie, Yeah, I see you don't know. However, many end users know some reasons.
Since the ChildWindows are essentially dialogues, what would you do with a few annoying dialogues which pop up for some reasons every 5 seconds on your screen, for example? Our end users just hide them nearly out of the screen.
So, in terms of usabiliity the dragging here is realized pretty poorly.

In other words the icon must not interfere to happy dragging of end users.

**Comment by timunie** [comment]
@DeputyOfCopyPaster 
please try:
```
HorizontalContentAlignment="Right"
VerticalContentAlignment="Bottom"
```
But please keep in mind that even this will not solve all the positioning issues you might have. And unfortunatally I don't have the time to rewrite all the stuff needed to archiev your goal.

> One personal oppinion from my side: If I were your customer and the `ChildWindow` would open so often, I would ask if this is the right `Control` / `UserInterface` for what you are trying to archiev. We can discuss this in a private gitter room, if you want to, please not here. 

I hope you understand that I will now leave this issue as it is right now.

Happy coding
Tim
