### ISSUE TITLE
Is it possible to make ChildWindow move outside of parent ?

### ISSUE THREAD

**Issue by GreatFireWall** [punker76/MahApps.Metro.SimpleChildWindow#105]

**Comment by timunie** [comment]
Hi @GreatFireWall ,

plaese see #103 and #104 . Does this answer your question?

Happy coding
Tim

**Comment by punker76** [comment]
@GreatFireWall If you mean to move really outside as a new window, then I must say no. I created this child window as a simple way to show a "window" inside an existing window.
