### ISSUE TITLE
Need advice, moving ChildWindow within mother's one.

### ISSUE THREAD

**Issue by DeputyOfCopyPaster** [punker76/MahApps.Metro.SimpleChildWindow#108]
![sample](https://user-images.githubusercontent.com/43616343/73613108-61549200-4603-11ea-8e0d-44b56ec47c28.gif)
Hello,
As far as I remember a movement of ChildWindow is limited by  so-called "Root-grid". Am I correct?
So, my question is, is it possible to move ChWindow _a little upper_, for example, **_over the mother window titlebar_**? If it is so, what should I do to get this behaviour?

As it is shown on the example of third-party application. 

DoC

**Comment by punker76** [comment]
@DeputyOfCopyPaster No, that's not possible in an easy way. If you use MahApps then you can try to override the MetroWindow default window style and re-span the Grid where the dialogs and child windows are shown.
