### ISSUE TITLE
doesn't work normal with MaterialDesignThemes.MahApps

### ISSUE THREAD

**Issue by lwqwag** [punker76/MahApps.Metro.SimpleChildWindow#113]
I have trouble when use MaterialDesignThemes.MahApps  version="0.1.1-ci1198,the newest version MaterialDesign and MaterialDesignThemes.MahApps .just like the image below.Do you have any advise?
![image](https://user-images.githubusercontent.com/29883542/77223250-b0e02480-6b95-11ea-859c-50f0b8f742c4.png)

![image](https://user-images.githubusercontent.com/29883542/77223261-d53c0100-6b95-11ea-936a-6737187eacbe.png)

**Comment by punker76** [comment]
@lwqwag This should now work again with 2.0.0-alpha0037

**Comment by lwqwag** [comment]
Thanks for your help!
