### ISSUE TITLE
ChildWindow from ChildWindow

### ISSUE THREAD

**Issue by eiredrake** [punker76/MahApps.Metro.SimpleChildWindow#115]
I have a situation where a dialog that launches a process will show a status dialog over it.

is there any way to show this progress dialog over the child window without having the main metro window replace it or cancelling the existing childwindow or something? Sort of a child of a child I guess it would be?

Liking what I am seeing so far by the way. Very easy to use your stuff. I appreciate that.

**Comment by timunie** [comment]
I think this is possible in the prelease / upcomming version. 

happy coding
Tim
