### ISSUE TITLE
when use validate in simplechildwindow, not display as expect

### ISSUE THREAD

**Issue by lwqwag** [punker76/MahApps.Metro.SimpleChildWindow#116]
i use validate property binding to xaml with validate, childwindow loaded first time validate errors not displayed as expect .when error has been cleared,i triggered an error,then the childwindow could display the validate error as expect just like the demo in  https://github.com/lwqwag/TestMahApp      Thx for your help.

**Comment by timunie** [comment]
Hi @lwqwag 

would it be an option for you to switch to `INotifyDataErrorInfo`? in my experience it is better than the old way validation worked. I can provide a sample if you wish. 

Happy coding
Tim

**Comment by lwqwag** [comment]
Hi @timunie 
Thanks for your reply.
INotifyDataErrorInfo validation method will be a option for me.
Your help is greatly appreciated.

**Comment by timunie** [comment]
@lwqwag I am sorry, but my Idea doesn't work either. It seems to be a bug, that it does not get the Validation when loaded. 
By the way: Many thanks for the great example. 👍 

Happy coding
Tim

**Comment by timunie** [comment]
I investigated this issue a bit further and it turned out that the validation works correct if I wrap the `Content` of the `ChildWindow`inside an `AdornerDekorator`. 

Here is my test branch. Maybe it helps for a solution: https://github.com/timunie/MahApps.Metro.SimpleChildWindow/tree/ValidationTest

Have a great weekend
Tim

**Comment by lwqwag** [comment]
@timunie I tested the branch you provided,and it worked well. It's  a great job!
Thanks a lot again.

**Comment by timunie** [comment]
Good morning @lwqwag 
please reopen this issue. I think it is a bug anyway, because my solution was just a workaround. 

Thanks,
Tim

**Comment by punker76** [comment]
>I think it is a bug anyway,

Yeah, it's a WPF thing :-(
