### ISSUE TITLE
Mahapps.Metro.SimpleChildWindow Nugget Package Issue

### ISSUE THREAD

**Issue by JustForFunDeveloper** [punker76/MahApps.Metro.SimpleChildWindow#118]
I'm not quite sure where but there seems to be an issue with an assembly reference when using the SimpleChildWindow Nugget Package.

Steps to reproduce:

1. Clean WPF .Net Project (4.7.2)
2. Install MahApps.Metro Nugget Package and use just a MetroWindow as main window.
3. Install MahApps.SimpleChildWindow Nugget Package and define a ChildWindow in xaml. (There is no need to do anthing in the code behind.)

It will throw the following exception as soon

```
this.InitializeComponent();
```
is called.

![AssemblyProblem](https://user-images.githubusercontent.com/31549249/84379552-4ebc1c00-abe6-11ea-9b56-f02d898e2757.png)

If i uninstall the SimpleChildWindow Nugget Package and reference just the library it will work fine.

**Comment by timunie** [comment]
Hi @JustForFunDeveloper 

Can you uplaod your sample or send the version numbers of your packages? 

Thank you and happy coding
Tim

**Comment by JustForFunDeveloper** [comment]
Here the version numbers as well my sample code.

![Versions](https://user-images.githubusercontent.com/31549249/84382137-7c0ac900-abea-11ea-9962-d247c66837a6.png)

Sampleproject:
[SimpleChildTest.zip](https://github.com/punker76/MahApps.Metro.SimpleChildWindow/files/4764528/SimpleChildTest.zip)

**Comment by timunie** [comment]
Oh I see. There is a prerelease v2.0.0 available. The version 1.5 only works with MahApps v1.6.5

**Comment by JustForFunDeveloper** [comment]
Ahhhh i get it now ... that's the reason why my compiled library worked. Didn't see that i had already the prerelease.

By the way ... where would i be able to see that this package is only working until 1.6.5?

Thank you very much tho!
