### ISSUE TITLE
Passing value with Close not working

### ISSUE THREAD

**Issue by realivanjx** [punker76/MahApps.Metro.SimpleChildWindow#121]
Hi,

I am trying to pass a value from child window after it is closed. Here is what I have done:

```
// in child window.
Close("test");
```

```
// parent window.
string result = await ChildWindowManager.ShowChildWindowAsync<string>(
     m_mainWindow,
     childWindow);
return result != null;
```

But the `result` is always null in parent's code. What am I missing here?

Thanks.

Versions: 
![image](https://user-images.githubusercontent.com/12814796/86502696-2b912080-bdd0-11ea-8a07-594bbb7386a3.png)

**Comment by punker76** [comment]
@realivanjx How is your `ChildWindowManager.ShowChildWindowAsync` implemented?

**Comment by realivanjx** [comment]
@punker76 I do not implement that function. I just called it. It is already there. Maybe i am using it wrong?

**Comment by punker76** [comment]
@realivanjx Sorry, my fault. Can you provide this sample?

**Comment by realivanjx** [comment]
@punker76 Sorry, I think now it is working. I was testing with the code i attached before but the result is always null. Sorry for interrupting.
