### ISSUE TITLE
Xaml Designer doesn't show ChildWindow

### ISSUE THREAD

**Issue by YannickHutter1993** [punker76/MahApps.Metro.SimpleChildWindow#13]
When I open the CoolChildWindow in Visual Studio 2013 I don't see the various content Elements such as Textbox etc. in the designer. All I see is a blue rectangle.

Is there a workaround for this or is this a XAML limitation?
![coolchildwindow](https://cloud.githubusercontent.com/assets/2711677/6819786/f3b1102a-d2c6-11e4-924f-6baecea3ecf6.png)

**Comment by punker76** [comment]
@YannickHutter1993 you can show the content by `IsOpen="True"`, this is by default set to `False`

![image](https://cloud.githubusercontent.com/assets/658431/8505459/3b1740ec-21e6-11e5-86b7-f4c853d9db7b.png)
