### ISSUE TITLE
Since 2.1.0 no dialog is shown

### ISSUE THREAD

**Issue by Symbai** [punker76/MahApps.Metro.SimpleChildWindow#131]
I've updated from 2.0.0 to 2.2.0 and noticed that no dialog alias child window is shown anymore. The constructor of the child window is called but its simply not there. Downgraded to 2.1.0 but problem persist. As soon as I downgrade to 2.0.0 dialogs are working as expected.

I'm using MetroApps Version 2.4.9, the latest version as of now. Was there any breaking change on 2.1.0 ?

I'm opening dialogs like this:

```C#
var dlg = new MyWindow() { IsModal = false };
var result = await this.ShowChildWindowAsync<bool>(dlg);
```

Where `MyWindow` is type of `ChildWindow`.

**Comment by punker76** [comment]
@Symbai Can you provide a full sample? Thx

**Comment by Symbai** [comment]
Sure here you go:

[WpfApp3.zip](https://github.com/punker76/MahApps.Metro.SimpleChildWindow/files/9940069/WpfApp3.zip)

2.2.0


https://user-images.githubusercontent.com/14368203/200020779-10c8b53b-9224-454c-be75-8d334471620e.mp4

2.0.0


https://user-images.githubusercontent.com/14368203/200020812-def620c5-c04e-4705-9002-28619ab3af7a.mp4


You might want to set height / width of child window to make it more visible.
