### ISSUE TITLE
ChildWindow closes on Escape pressed

### ISSUE THREAD

**Issue by 4ipalino** [punker76/MahApps.Metro.SimpleChildWindow#14]
Hi,

when i press Esc the ChildWindow gets closed. I tried to avoid this behavior with the OnKeyDown Event but this didn´t work. Are there any appproaches to avoid that the ChildWindow gets closed until i say it explicit from code.

**Comment by punker76** [comment]
@4ipalino that's not changable now, i'll add this in the next release...
