### ISSUE TITLE
ShowSimpleChildWindow in VB.Net

### ISSUE THREAD

**Issue by furiousbuilder** [punker76/MahApps.Metro.SimpleChildWindow#15]
Hi, 

I've a usercontrol named setupchildwindow, I've imported MahApps.Metro.Controls but I'm not able to use 
"Me.ShowChildWindowAsync(new setupchildwindow())" how to make my childwindow appear ? 

Thanks !

**Comment by punker76** [comment]
@furiousbuilder can you explain a little bit more? is there any bad output? or exception or something else?

**Comment by furiousbuilder** [comment]
ShowChldWindowAsync is not defined, I work with VS 2013 and net framework 4.5. Is there any other way to show a simplechildwindow in VB.Net ?

**Comment by punker76** [comment]
@furiousbuilder any news for this? can you provide a full stack trace?

**Comment by furiousbuilder** [comment]
Hi,


I haven't code for 2 months due to some exams and I just formatted my drive to dual boot W10 and Mac OS X, so I need to reinstall visual studio but I think that the problem has been corrected, when VS will be reinstalled I'll provide you some code :)

**Comment by furiousbuilder** [comment]
MsgBox are now working in 1.2.0 but I'm still not able to use ShowMessageAsync, because it seems to be not declared

**Comment by frogcrush** [comment]
Make sure you import MahApps.Metro.Controls.Dialogs, as it provides the override methods.
