### ISSUE TITLE
Modify main form from SimpleChildWindow

### ISSUE THREAD

**Issue by furiousbuilder** [punker76/MahApps.Metro.SimpleChildWindow#16]
Hi, I have a problem : 
I'm trying to modify my main form with a Button on the SimpleChildWindow but it doesn't work.
I'm using this code in VB.Net : 

Dim main As New MainWindow
Dim Nom As String = textbox1.Text
Dim Prenom As String = textbox2.Text
main.usernametext.Text = Nom & " " & Prenom

Here, usernametext is just a Label. The code give any error but nothing happens. Can I have help ? 
Thank you !

**Comment by punker76** [comment]
@furiousbuilder can you provide more source? or just an error or something else? thx

**Comment by furiousbuilder** [comment]
I don't have error, the label still have the same text like I haven't clicked on the button... Do you want that I upload the code of the button ?

**Comment by punker76** [comment]
@furiousbuilder if its possible your style of the child window and the button click event...

**Comment by furiousbuilder** [comment]
Here is the code : http://pastebin.com/0PAHp3Hn
All the code work except main.roundPB.Source = bitmapimage and main.usernametext.Text = Nom & " " & Prenom
Dim main As New mainwindow is not here but it has been defined before

**Comment by furiousbuilder** [comment]
I'm not able to show a MsgBox too, it makes the app crash.

**Comment by punker76** [comment]
@furiousbuilder any news for this? if not, can you provide a full stacktrace from the crash? i think it's not caused by the child window.

**Comment by furiousbuilder** [comment]
Hi,


I haven't code for 2 months due to some exams and I just formatted my drive to dual boot W10 and Mac OS X, so I need to reinstall visual studio to provide you some code but the problem is clearly not solved, interacting with everything else outside of the childwindow is impossible for me (showing a msgbox, modifying the main window...) but if my memory is great, I have no error messages, the action is just runing without end, so I can't close the app without freeze. I will try to take a video soon

**Comment by furiousbuilder** [comment]
Okay so now I'm able to show MsgBox, but I'm not able to control main form, nothing happen, even a simple
Dim main As New MainWindow
main.Title = "TitleChanged"
