### ISSUE TITLE
Application hang with SCW

### ISSUE THREAD

**Issue by RiderOfTheli** [punker76/MahApps.Metro.SimpleChildWindow#17]
Hi Jan,

I saw that someone already ask you about that, but I would like to raise a hand that the problem exists ;)

When I want to change binding for IsOpen VS crash and there is nothing I can do with it. Event viewer shows only 1002 error with source: Application Hang.

Here you can find full event general info:

The program devenv.exe version 14.0.22823.1 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Action Center control panel.
 Process ID: 24c8
 Start Time: 01d0888fc1814b40
 Termination Time: 32
 Application Path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe
 Report Id: 2e089999-f483-11e4-827c-402cf4c7fed8
 Faulting package full name: 
 Faulting package-relative application ID: 

I was trying to fix it with sfc /scannow and then manully fix crashed files for VS - no result. 

Thank you for any suggestions,

**Comment by punker76** [comment]
@RiderOfTheli are you using vs 2015 ctp? maybe its an issue with it.

**Comment by RiderOfTheli** [comment]
Yep, but in 2012, 2013 - the same.

**Comment by punker76** [comment]
@RiderOfTheli "When I want to change binding for IsOpen" do you mean changing in designer?

**Comment by RiderOfTheli** [comment]
Yes. I'm not using code behind in here because I want to do this in 'proper mvvm'. I'll check with code behind, just for testing purpose it this works, but in designer - app hangs.

**Comment by RiderOfTheli** [comment]
@punker76 with call in code-behind under MetroWindow_Loaded and button_Click it works. In xaml when binding IsOpen visual studio died again.
