### ISSUE TITLE
Designer support

### ISSUE THREAD

**Issue by frogcrush** [punker76/MahApps.Metro.SimpleChildWindow#23]
I don't know if this affects only me, but I don't have any designer support. All I have is a blank grid in the designer. I still have full XAML editor support. 
![no-designer-support](https://cloud.githubusercontent.com/assets/6116333/10983848/0c2b7046-83ca-11e5-94c1-c66afb93ee9f.png)

**Comment by robg66** [comment]
I got the same problem. 
Any solutions for this?

**Comment by punker76** [comment]
@robg66 @frogcrush as a workaround set `IsOpen="True"`

**Comment by robg66** [comment]
Thanks it works

**Comment by frogcrush** [comment]
Yes, this works perfectly.
