### ISSUE TITLE
Child window appears "beneath" validation errors

### ISSUE THREAD

**Issue by agc93** [punker76/MahApps.Metro.SimpleChildWindow#24]
I have a simple WPF app with "standard" WPF validation (i.e. _IDataErrorInfo_ and _ValidatesOnDataErrors_ ) enabled, and when opening the child window, the outlines left by validation errors appear on top of the child window (the field's stay below it).

![screenshot 8](https://cloud.githubusercontent.com/assets/1369269/11772203/b3053622-a265-11e5-825a-dca4dfb95ab6.png)

I have tried updating the `Panel.ZIndex` property to something extremely high (5000) and it does not resolve the issue.

Note that this may be an issue with MahApps.Metro's implementation of validation errors, so let me know if this should be raised in that repo, or if you need any more information.

Markup (trimmed) for ChildWindow:

``` xml
 <s:ChildWindow
        IsOpen="{Binding Path=IsAboutWindowVisible}"
        HorizontalContentAlignment="Center"
        VerticalContentAlignment="Center"
        Padding="15"
        ChildWindowImage="Information"
        Title="Help/About"
        CloseOnOverlay="True"
        GlowBrush="{DynamicResource AccentColorBrush}">
</s:ChildWindow
```

**Comment by punker76** [comment]
@agc93 You can prevent this if you put your window/usercontrol content (not the child window content) in a `AdornerDecorator`.

**Comment by punker76** [comment]
@agc93 Can I close this?

**Comment by agc93** [comment]
@punker76 yeah close this one: haven't worked on the application for a while
