### ISSUE TITLE
Prevent moving the window completly outside of the parent window

### ISSUE THREAD

**Issue by TheFlow0360** [punker76/MahApps.Metro.SimpleChildWindow#29]
When using `AllowMove=True` the dialog can be moved outside of view. It would be good, if moving the mouse cursor outside of the bounds of the parent window would be prevented, so that the child window can never completly go out of view.

**Comment by TheFlow0360** [comment]
@punker76 this can be tagged as "enhancement", too

**Comment by INGCRENGIFO** [comment]
@punker76 and @TheFlow0360 there is a date set for the implementation of the improvement ?? I just installed mahapps from nuget.
