### ISSUE TITLE
AllowMove does not work.

### ISSUE THREAD

**Issue by AndreasSchmid1** [punker76/MahApps.Metro.SimpleChildWindow#30]
I added a ChildWindow to my Mainwindow Content but the AllowMove property did not enable ChildWindow moving. Did I miss enabling something to get this feature working?

My current code:

`<simpleChildWindow:ChildWindow
                 IsOpen="{Binding IsChildWindowOpenOrNotProperty}"
                 HorizontalContentAlignment="Stretch"
                 VerticalContentAlignment="Stretch"
                 Padding="15"
AllowMove=true
                 ChildWindowImage="Error"
                 Title="TestChild 1">
  <Grid>
  </Grid>
</simpleChildWindow:ChildWindow>`

**Comment by TheFlow0360** [comment]
i had this problem to, the reason is that AllowMove is not compatible with `HorizontalContentAlignment="Stretch" VerticalContentAlignment="Stretch"`

**Comment by AndreasSchmid1** [comment]
Thank you. That was the problem!
