### ISSUE TITLE
Window closes when pressing escape inside an openfiledialog

### ISSUE THREAD

**Issue by elios264** [punker76/MahApps.Metro.SimpleChildWindow#33]
I Have a ChildWindow opened and then I opened an OpenFileDialog, when I pressed the escape key, on the openfiledialog the ChildWindow closed as well
![animation2](https://cloud.githubusercontent.com/assets/15863852/15950859/60759b5a-2e78-11e6-9fe7-7f9bc42121ef.gif)

**Comment by punker76** [comment]
@elios264 Is fixed now and will be available with v1.3.2
