### ISSUE TITLE
Close() method raising error

### ISSUE THREAD

**Issue by wizkidd** [punker76/MahApps.Metro.SimpleChildWindow#35]
I'm calling the 

`await ShowChildWindowAsync(windowA)` 
 `windowA.Close()` 
`await ShowChildWindowAsync(windowA)` 

in succession, and getting the error "The provided child window is already visible in the specified window."

Do I need to await Close in anyway?

**Comment by punker76** [comment]
@wizkidd Can you please detail explain what do you want? This lines seems wrong, cause you open a child window, close the window and want to show again the child window on a closed window?

**Comment by punker76** [comment]
@wizkidd The Close method sets the IsOpen property to false and is not awaitable. So if you want to show a child window after closing another you can subscribe to IsOpenChangedEvent or ClosingFinishedEvent to handle this.
