### ISSUE TITLE
Block accessing main window when child window is opened

### ISSUE THREAD

**Issue by sandrasathish** [punker76/MahApps.Metro.SimpleChildWindow#37]
When child window is opened which smaller than main window. I am able to access controls in the main window.

**Comment by eluchsinger** [comment]
@sandrasathish does your childwindow have the `Width` and `Height `Properties set?

**Comment by punker76** [comment]
@sandrasathish @eluchsinger To set width and height of the window then set `ChildWindowWidth` and `ChildWindowHeight`

**Comment by sandrasathish** [comment]
Thanks its worked.
