### ISSUE TITLE
PART_HeaderThumb prevents icon click

### ISSUE THREAD

**Issue by shawnshaddock** [punker76/MahApps.Metro.SimpleChildWindow#39]
Please move PART_HeaderThumb to Column 1 and remove ColumnSpan 2 so that it doesn't overlay the icon and prevent the ability to click it when AllowMove is true. Standard behavior of window icons is to provide a menu on click, and not the ability to drag and move the window.

**Comment by punker76** [comment]
@shawnshaddock I will prevent this for now in v1.3.2, but a menu will not be shown, cause this is a fake window, it's a ContentControl. I don't know if I should add a tiny menu with first only one item which closes the child window...
