### ISSUE TITLE
IsAutoCloseEnabled="True" for SimpleChildWindow - possible?

### ISSUE THREAD

**Issue by RiderOfTheli** [punker76/MahApps.Metro.SimpleChildWindow#41]
Hi,

I would like to ask if it's possible to add **AutoClose** to the SimpleChildWindow, just like **Flyouts** has in MahApps.Metro project? **IsAutoCloseEnabled="True"** with proper interval.

Thank you :)

**Comment by punker76** [comment]
@RiderOfTheli This will be available in 1.4.0
