### ISSUE TITLE
CloseButtonCommand Fire Only first Time

### ISSUE THREAD

**Issue by Speuline** [punker76/MahApps.Metro.SimpleChildWindow#56]
Hello, 
Is it just me or the closeButtonCommand only fire the first time you use it?

Second time, the windows close but nothing happens in the viewModel.

**Comment by punker76** [comment]
@Speuline Yeah, seems like it's my fault...

https://github.com/punker76/MahApps.Metro.SimpleChildWindow/blob/32f64727352dc5c167e552a908e219800f87e9b9/src/MahApps.Metro.SimpleChildWindow/ChildWindow.cs#L1119-L1120
