### ISSUE TITLE
CloseButton not visible with light mahapps theme

### ISSUE THREAD

**Issue by ThuCommix** [punker76/MahApps.Metro.SimpleChildWindow#57]
Hello, I recently started using your library and noticed that when a light theme is selected (LightBase) the close button is not visible because its also whiteish.
![t1](https://user-images.githubusercontent.com/3823625/31569912-40dd5082-b07f-11e7-84f2-8b39f3dbb947.png)
![t2](https://user-images.githubusercontent.com/3823625/31569913-42b8dbec-b07f-11e7-88e3-3659bd45b97c.png)

The second image is clicking the close button.

**Comment by punker76** [comment]
@ThuCommix I can't reproduce this issue, so can you post which version of MahApps and SimpleChildWindow you are using? How do you specify the MahApps resources?
