### ISSUE TITLE
Text should be in "normal case" instead of upper case

### ISSUE THREAD

**Issue by liweys** [punker76/MahApps.Metro.SimpleChildWindow#62]
Seems everything is converted uppercase by default. I think this is not user wants. If I want uppercases somewhere, I will convert it (or specify some property in style) myself. 
By the way how to keep/set all widgets to use "normal case" (original case) ?

**Comment by punker76** [comment]
@liweys I don't know which code do you mean, but here is the default the `Normal` value...

https://github.com/punker76/MahApps.Metro.SimpleChildWindow/blob/69ed7966d8067fc8a764523f645d0194cf1acf51/src/MahApps.Metro.SimpleChildWindow/ChildWindow.cs#L156
