### ISSUE TITLE
Strange things happen if window devided by  grid rows.

### ISSUE THREAD

**Issue by DeputyOfCopyPaster** [punker76/MahApps.Metro.SimpleChildWindow#77]
Hello there,
I am a newcomer, just testing 'SimpleChildWindow' for my needs.

I faced with a stuff as follows:

![mahapps_window_with_no_grid](https://user-images.githubusercontent.com/43616343/46786372-50f91380-cd3d-11e8-8ed8-5b072b31940b.png)
That's working properly. I used this method:

```
 private async void button_Click(object sender, RoutedEventArgs e)
        {
            await this.ShowChildWindowAsync(new Parameter_01() { IsModal = true, AllowMove = true }, RootGrid);
        }
```

![mahapps_window_with_grid](https://user-images.githubusercontent.com/43616343/46786426-79810d80-cd3d-11e8-8716-021f45728b1d.png)
Just I added the needed rows in the 'Rootgrid'. And everything became bad.
Could someone make some comments on this, I don't know, if this is an issue.

Thanks in advance.

**Comment by punker76** [comment]
@DeputyOfCopyPaster Please can you post your grid layout? it seems like your Rootgrid is not any more the "root" grid.

**Comment by DeputyOfCopyPaster** [comment]
> @DeputyOfCopyPaster Please can you post your grid layout? it seems like your Rootgrid is not any more the "root" grid.

Yes, of course!

```
<Controls:MetroWindow
    x:Class="MahappsChildWindowTest_01.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:Controls="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:local="clr-namespace:MahappsChildWindowTest_01"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    Title="MainWindow"
    Width="800"
    Height="600"
    MinWidth="800"
    MinHeight="600"
    mc:Ignorable="d">

    <Grid x:Name="RootGrid" ShowGridLines="True">

            <Grid.RowDefinitions>
            <RowDefinition Height="80" />
            <RowDefinition Height="*" />
            <RowDefinition Height="200" />
            </Grid.RowDefinitions> 
        
        <Button x:Name="button" Content="Result" HorizontalAlignment="Left" VerticalAlignment="Top" Width="75" Click="button_Click" Margin="550,79,0,0" Grid.Row="2"  />

    </Grid>
</Controls:MetroWindow>

```
So far, I hadn't got any grids, except 'RootGrid'.

**Comment by DeputyOfCopyPaster** [comment]
Solved!
If you're going to use 'SimpleChildWindow', don't use that grid that comes by default by a project creating.
You must leave default grid to be virgin. In default grid can be next grid which may be formatted by you.
Otherwise you will get an issue as described above.

**This is wrong approach:**

 ```
<Grid x:Name="RootGrid" ShowGridLines="True"> <!--default grid-->

            <Grid.RowDefinitions>
            <RowDefinition Height="80" />
            <RowDefinition Height="*" />
            <RowDefinition Height="200" />
            </Grid.RowDefinitions> 

<Grid > <!-- default grid-->
```
**This is approach that solved issue:**

```
<Grid x:Name="RootGrid" >  <!-- default grid-->
<Grid ShowGridLines="True">  <!-- a grid to be formatted for your needs-->

            <Grid.RowDefinitions>
            <RowDefinition Height="80" />
            <RowDefinition Height="*" />
            <RowDefinition Height="200" />
            </Grid.RowDefinitions> 

<Grid > <!-- a grid to be formatted for your needs-->
<Grid> <!-- default grid-->
```
Solved thanks to **Punker76's** a little hint about.
