### ISSUE TITLE
Needs Mahapps.Metro 1.0.0.0

### ISSUE THREAD

**Issue by riegaz** [punker76/MahApps.Metro.SimpleChildWindow#8]
In VS I get the following error when using the latest prerelease of Mahapps.Metro (1.1.2.7).

Error	1	The type 'MahApps.Metro.Controls.MetroWindow' is defined in an assembly that is not referenced. You must add a reference to assembly 'MahApps.Metro, Version=1.0.0.0, Culture=neutral, PublicKeyToken=f4fb5a3c4d1e5b4f'.

This should be fixed.

**Comment by punker76** [comment]
fixed with v1.1.0 701176e3b156621b82c7aeec939444ebe5dd857a

**Comment by riegaz** [comment]
That was fast, it is working now! Thanks!
