### ISSUE TITLE
Close button is unthemed

### ISSUE THREAD

**Issue by Symbai** [punker76/MahApps.Metro.SimpleChildWindow#94]
Updated to Mahapps 2 beta. The close button on child windows are unthemed. Did I miss something or is this a bug?

![image](https://user-images.githubusercontent.com/14368203/63635002-f9aa1c00-c64c-11e9-9d04-5d1fb2868775.png)

**Comment by timunie** [comment]
@Symbai I think it is a bug that comes from the renaming of the Style Keys in MahApps Metro.  I have opened a PR on this issue, see #93 . 

Happy coding
Tim

**Comment by Symbai** [comment]
Thanks, I've subscribed but leave this issue open as I don't know if your PR definitely fixes it. Punker76 can close this issue if it does.

**Comment by timunie** [comment]
Yes,  please leave it open. I will have a look for a workaround tomorrow. 

Happy coding
Tim

**Comment by punker76** [comment]
Related to #93 and #92
